# General setup to build and run tests on the project whenever committing
sudo: required
services:
  - docker
before_install:
  - docker build -t jahhasangjekaj/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jahhasangjekaj/docker-react npm run test -- --coverage

# Deploy to production only when thera are changes to master branch
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-269924676398"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
