sudo: required
services:
  - docker
before_install:
  - docker build -t jahhasangjekaj/docker-react -f Dockerfile.dev .
script:
  - docker run jahhasangjekaj/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-269924676398"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
